source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'angularjs-rails'
gem 'haml-rails'
gem 'rails_12factor', group: :production
gem 'sprockets'
gem 'bootstrap-sass'
gem 'therubyracer'
gem 'less-rails'
gem 'select2-rails', '3.5.9.1'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'toastr-rails'
gem 'jquery-minicolors-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'rails-i18n'
gem 'i18n_generators'
gem 'paranoia'
gem 'kaminari'
gem 'dotenv-deployment'
gem 'sidekiq'
gem 'sinatra', require: false
gem 'slim'

group :development, :test do
  gem 'rubocop'
  gem 'pry', '< 0.10.0'
  gem 'pry-rails'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'capybara'
  gem 'capybara-email'
  gem 'capybara-webkit'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'rspec-collection_matchers'
  gem 'rspec-legacy_formatters'
  gem 'rspec-support'
  gem 'rspec-core'
  gem 'guard-rspec'
  gem 'growl'
  gem 'webrat'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spork'
  gem 'faker'
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
  gem 'rspec_junit_formatter'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'dotenv-rails'
  gem 'letter_opener_web'
  gem 'erb2haml'
end
